import {generate,lesson,steps,peers,conflicts,candidates} from './engine.js';
const $=id=>document.getElementById(id),key='sudoku-discovery-v1';
let mode='play',type='single',selected=-1,memo=false,history=[],hintStep=null,hintLevel=0,round=0,completed=false,state;
const titles={single:'이 칸에는 하나만',hidden:'이 숫자는 여기만'};
function fresh(){const board=generate();return {givens:board,board:[...board],notes:Array.from({length:36},()=>[]),hints:0};}
function save(){if(mode==='play')try{localStorage.setItem(key,JSON.stringify(state));}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem(key));if(s&&['board','givens'].every(k=>Array.isArray(s[k])&&s[k].length===36&&s[k].every(n=>Number.isInteger(n)&&n>=0&&n<=6))&&s.givens.every((n,i)=>!n||s.board[i]===n)&&Array.isArray(s.notes)&&s.notes.length===36&&s.notes.every(a=>Array.isArray(a)&&a.every(n=>Number.isInteger(n)&&n>0&&n<7))){s.hints=Number.isInteger(s.hints)?s.hints:0;return s;}}catch{}return fresh();}
function resetUI(){selected=-1;history=[];hintStep=null;hintLevel=0;completed=false;$('success').hidden=true;memo=false;$('memo').classList.remove('active');$('memo').setAttribute('aria-pressed','false');}
function startLesson(t){if(mode==='play')save();mode='learn';type=t;round=0;loadLesson();}
function loadLesson(){resetUI();const l=lesson(type);state={givens:l.board,board:[...l.board],notes:Array.from({length:36},()=>[]),hints:0};hintStep=l.step;selected=type==='single'?hintStep.cell:-1;if(round===0)hintLevel=1;message(round===0?question():`혼자 적용해볼까요? ${type==='single'?'테두리 칸에 가능한 숫자를 찾아보세요.':`${hintStep.value}이 들어갈 자리가 하나뿐인 곳을 찾아보세요.`}`);render();}
function question(){return hintStep.type==='single'?'테두리 칸에 들어갈 수 있는 숫자는 무엇일까요?':`${unitName(hintStep)}에서 ${hintStep.value}이 들어갈 자리를 찾아보세요.`;}
function unitName(s){return s.unitIndex<6?'강조된 가로줄':s.unitIndex<12?'강조된 세로줄':'강조된 작은 상자';}
function message(text){$('message').textContent=text;}
function evidence(s){return s.type==='single'?peers(s.cell).filter(i=>state.board[i]):[...new Set(s.unit.filter(i=>!state.board[i]&&i!==s.cell).flatMap(i=>peers(i).filter(j=>state.board[j]===s.value)))];}
function render(){ $('learn').classList.toggle('active',mode==='learn');$('play').classList.toggle('active',mode==='play');$('lesson-picker').hidden=mode!=='learn';document.querySelectorAll('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===type));$('tag').textContent=mode==='learn'?`풀이 방법 · ${round===0?'함께 발견':'혼자 적용'}`:'6 × 6 · 자유 풀이';$('title').textContent=mode==='learn'?titles[type]:'한 칸씩 찾아봐요';$('new').textContent=mode==='learn'?'다른 연습':'새 문제';$('board').replaceChildren();const bad=conflicts(state.board),related=selected>=0?peers(selected):[],clues=hintStep&&hintLevel>=2?evidence(hintStep):[];
 state.board.forEach((n,i)=>{const b=document.createElement('button');b.className='cell';b.classList.toggle('given',!!state.givens[i]);b.classList.toggle('related',related.includes(i));b.classList.toggle('same',!!n&&selected>=0&&n===state.board[selected]);b.classList.toggle('clue',clues.includes(i)||(hintStep?.type==='hidden'&&(hintLevel>=1||mode==='learn')&&hintStep.unit.includes(i)));b.classList.toggle('target',!!hintStep&&((hintStep.type==='single'&&(mode==='learn'||hintLevel>0))||hintLevel>=3)&&i===hintStep.cell);b.classList.toggle('selected',i===selected);b.classList.toggle('conflict',bad.includes(i));b.setAttribute('aria-label',`${Math.floor(i/6)+1}행 ${i%6+1}열, ${n||'빈칸'}${state.givens[i]?', 주어진 숫자':''}`);b.setAttribute('aria-pressed',String(i===selected));if(n)b.textContent=n;else{const ns=document.createElement('span');ns.className='notes';for(let k=1;k<=6;k++){const el=document.createElement('span');el.textContent=state.notes[i].includes(k)?k:'';ns.append(el);}b.append(ns);}b.onclick=()=>{selected=i;render();};$('board').append(b);});$('undo').disabled=!history.length;$('hint').disabled=completed;
}
function checkpoint(){history.push(JSON.stringify({board:state.board,notes:state.notes}));}
function input(n){if(completed)return;if(selected<0){message('먼저 빈칸을 선택해주세요.');return;}if(state.givens[selected]){message('처음부터 주어진 숫자는 바꿀 수 없어요.');return;}if(mode==='learn'&&!memo&&n&&(selected!==hintStep.cell||n!==hintStep.value)){message('아직 이번 단서가 가리키는 답은 아니에요. 가로 · 세로 · 상자를 다시 살펴보세요.');return;}checkpoint();if(memo&&n){if(state.board[selected]){history.pop();message('메모는 빈칸에 적을 수 있어요.');return;}const a=state.notes[selected];state.notes[selected]=a.includes(n)?a.filter(v=>v!==n):[...a,n].sort();message('메모는 가능한 숫자를 적는 공간이에요.');}else{state.board[selected]=n;state.notes[selected]=[];if(n)peers(selected).forEach(i=>state.notes[i]=state.notes[i].filter(v=>v!==n));const bad=conflicts(state.board);message(bad.length?'같은 가로줄 · 세로줄 · 상자에 겹치는 숫자가 있어요. 표시된 칸을 확인해보세요.':'숫자를 적었어요. 다음 단서를 찾아보세요.');if(mode==='learn'&&n){completed=true;showSuccess(`${n}이 들어가는 이유: ${hintStep.type==='single'?'다른 숫자는 같은 가로줄 · 세로줄 · 상자에 이미 있어요.':`이 구역에서 ${n}이 가능한 자리가 이 칸뿐이에요.`}`,round===0?'혼자 적용해보기':'다시 연습하기',()=>{round=round===0?1:0;loadLesson();});}else if(state.board.every(Boolean)&&!bad.length){completed=true;showSuccess(`완성했어요! 빈칸 ${state.givens.filter(n=>!n).length}개를 채웠어요. 힌트 버튼은 ${state.hints}번 사용했어요.`,'다음 문제',newGame);}}
 if(mode==='play'){hintStep=null;hintLevel=0;}save();render();}
function showSuccess(text,label,action){const box=$('success');box.replaceChildren();box.hidden=false;const p=document.createElement('p');p.textContent=text;const b=document.createElement('button');b.textContent=label;b.onclick=action;box.append(p,b);}
function newGame(){if(mode==='learn'){loadLesson();return;}resetUI();state=fresh();save();message('새로운 퍼즐이에요. 빈칸을 선택해 시작하세요.');render();}
$('learn').onclick=()=>{if(mode!=='learn')startLesson(type);};$('play').onclick=()=>{if(mode==='play')return;mode='play';resetUI();state=restore();message('풀던 문제를 이어서 풀어보세요.');render();};document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>startLesson(b.dataset.type));$('new').onclick=()=>{if(mode==='play'&&state.board.some((n,i)=>n!==state.givens[i])&&!completed&&!confirm('풀던 문제를 새 문제로 바꿀까요?'))return;newGame();};
for(let n=1;n<=6;n++){const b=document.createElement('button');b.textContent=n;b.setAttribute('aria-label',`${n} 입력`);b.onclick=()=>input(n);$('numbers').append(b);}
$('memo').onclick=()=>{memo=!memo;$('memo').classList.toggle('active',memo);$('memo').setAttribute('aria-pressed',String(memo));};$('erase').onclick=()=>input(0);$('undo').onclick=()=>{if(!history.length)return;const prev=JSON.parse(history.pop());Object.assign(state,prev);completed=false;$('success').hidden=true;if(mode==='play'){hintStep=null;hintLevel=0;}save();message('마지막 입력을 되돌렸어요.');render();};
$('hint').onclick=()=>{if(conflicts(state.board).length){message('먼저 겹치는 숫자를 수정해보세요.');return;}if(!hintStep){hintStep=steps(state.board)[0];if(!hintStep){message('현재 입력을 다시 확인해보세요. 지금은 배운 두 방법으로 찾을 수 있는 다음 수가 없어요. 되돌리기로 앞선 선택을 살펴볼 수 있어요.');return;}}hintLevel=Math.min(3,hintLevel+1);state.hints++;if(hintLevel===1)message(question());else if(hintLevel===2)message(hintStep.type==='single'?'노란색 숫자를 살펴보세요. 같은 가로줄 · 세로줄 · 상자에 있는 숫자는 들어갈 수 없어요.':`${unitName(hintStep)}의 빈칸을 살펴보세요. 노란색 ${hintStep.value} 때문에 들어갈 수 없는 자리를 제외해보세요.`);else{selected=hintStep.cell;message(`테두리 칸에는 ${hintStep.value}이 들어가요. ${hintStep.type==='single'?'다른 숫자는 모두 제외돼요.':'이 구역에서 가능한 자리가 여기뿐이에요.'} 직접 숫자를 눌러 채워보세요.`);}save();render();};
document.addEventListener('keydown',e=>{if(e.target.tagName==='BUTTON'&&['Enter',' '].includes(e.key))return;if(/^[1-6]$/.test(e.key))input(Number(e.key));if(['Backspace','Delete'].includes(e.key)){e.preventDefault();input(0);}const d={ArrowLeft:-1,ArrowRight:1,ArrowUp:-6,ArrowDown:6}[e.key];if(d){e.preventDefault();selected=selected<0?0:Math.max(0,Math.min(35,selected+d));render();}});state=restore();if(state.board.every(Boolean)&&!conflicts(state.board).length){completed=true;showSuccess('완성한 문제예요. 다음 문제에도 도전해보세요.','다음 문제',newGame);}render();
